### ISSUE TITLE
tf: invalid memory access

### ISSUE THREAD

**Issue by cboxdoerfer** [Alexey-Yakovenko/deadbeef#1248]
group format string: 

```
$if($strcmp(%genre%,Classical),%composer%,$if([%band%],%band%,%album artist%)) | ($left(%year%,4)) %album% $if($greater(%totaldiscs%,1),- Disc: %discnumber%/%totaldiscs%) - \[%codec%\]
```

Valgrind output:

```
==18329== Invalid read of size 1
==18329==    at 0x41E839: u8_inc (utf8.c:288)
==18329==    by 0x41E942: u8_charcpy (utf8.c:278)
==18329==    by 0x422653: tf_eval_int (tf.c:297)
==18329==    by 0x4238E3: tf_eval (tf.c:102)
==18329==    by 0x6054F6A: pl_common_get_group (plcommon.c:1590)
==18329==    by 0x6042146: ddb_listview_build_groups (ddblistview.c:3324)
==18329==    by 0x6046094: ddb_listview_update_fonts (ddblistview.c:935)
==18329==    by 0x604615B: ddb_listview_list_configure_event (ddblistview.c:620)
==18329==    by 0x64A8F3C: ??? (in /usr/lib/libgtk-3.so.0.1600.6)
==18329==    by 0x7FBF2F4: g_closure_invoke (in /usr/lib/libgobject-2.0.so.0.4400.1)
==18329==    by 0x7FD102B: ??? (in /usr/lib/libgobject-2.0.so.0.4400.1)
==18329==    by 0x7FD9194: g_signal_emit_valist (in /usr/lib/libgobject-2.0.so.0.4400.1)
==18329==  Address 0x2e9841fe is 0 bytes after a block of size 190 alloc'd
==18329==    at 0x4C29E6F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18329==    by 0x423E95: tf_compile (tf.c:901)
==18329==    by 0x60468EF: main_playlist_init (mainplaylist.c:304)
==18329==    by 0x6063CC1: w_playlist_create (widgets.c:2401)
==18329==    by 0x6061B10: w_create (widgets.c:955)
==18329==    by 0x6061F24: w_create_from_string (widgets.c:497)
==18329==    by 0x6061F9A: w_create_from_string (widgets.c:552)
==18329==    by 0x6061F9A: w_create_from_string (widgets.c:552)
==18329==    by 0x6061F9A: w_create_from_string (widgets.c:552)
==18329==    by 0x6061F9A: w_create_from_string (widgets.c:552)
==18329==    by 0x6061F9A: w_create_from_string (widgets.c:552)
==18329==    by 0x6023857: init_widget_layout (gtkui.c:896)
==18329==
```

**Comment by cboxdoerfer** [comment]
Fixed with https://github.com/Alexey-Yakovenko/deadbeef/commit/3515472fe0f2692ec05ad78d805429473ae2c918

**Comment by Alexey-Yakovenko** [comment]
ok, so we know padding solves it.. but I still don't know why it happens, so will keep the bug open for now.

**Comment by cboxdoerfer** [comment]
Do you want me to send you the file?

**Comment by Alexey-Yakovenko** [comment]
This might help. It might be that this bug only happens on linux when called from a specific place like the GTKUI grouping code, while I was testing on OSX.

**Comment by Alexey-Yakovenko** [comment]
No sense keeping this bug open, with workaround in place. There's no progress on this.
