### ISSUE TITLE
deadbeef fails to start up with "ffmpeg: too many extensions, max is 256", then segmentation fault.

### ISSUE THREAD

**Issue by felixbecker2** [Alexey-Yakovenko/deadbeef#1755]
I am using deadbeef, version 0.7.2, on Arch Linux. The bug report is valid both against the Arch Linux package and a custom build of deadbeef.

When deadbeef starts up with the ffmpeg-plugin, it fails with
`ffmpeg: too many extensions, max is 256`, followed by a `Segmentation Fault`.

I use a custom compiled ffmpeg with as many options available as I could ffmpeg to get compile (so, a lot of decoders and supported file formats).

When I compile deadbeef without ffmpeg-plugin (`./configure`-option `--disable-ffmpeg`), then deadbeef starts up normally.

Here is the complete output of combined stdout and stderr when running `deadbeef` (`--enable-ffmpeg`-compiled):

    starting deadbeef 0.7.2
    server_start
    searching for GUI plugins in /home/felics/.local/lib64/deadbeef
    searching for GUI plugins in /home/felics/.local/lib/deadbeef
    searching for GUI plugins in /usr/lib/deadbeef
    load_plugin_dir /usr/lib/deadbeef: scandir found 117 files
    found gui plugin ddb_gui_GTK2.so
    added GTK2 gui plugin
    load gui plugin
    checking GUI plugin: GTK2
    selected GUI plugin not found or failed to load, trying to find another GUI plugin
    the plugin not found or failed to load
    the plugin not found or failed to load
    loading plugin /usr/lib/deadbeef/ddb_gui_GTK2.so
    loading plugins from /home/felics/.local/lib64/deadbeef
    loading plugins from /home/felics/.local/lib/deadbeef
    loading plugins from /usr/lib/deadbeef
    load_plugin_dir /usr/lib/deadbeef: scandir found 117 files
    loading plugin /usr/lib/deadbeef/aac.so
    loading plugin /usr/lib/deadbeef/adplug.so
    loading plugin /usr/lib/deadbeef/alac.so
    loading plugin /usr/lib/deadbeef/alsa.so
    loading plugin /usr/lib/deadbeef/artwork.so
    loading plugin /usr/lib/deadbeef/cas_ofr.so
    loading plugin /usr/lib/deadbeef/cdda.so
    loading plugin /usr/lib/deadbeef/converter.so
    loading plugin /usr/lib/deadbeef/converter_gtk2.so
    loading plugin /usr/lib/deadbeef/dca.so
    loading plugin /usr/lib/deadbeef/ddb_ao.so
    loading plugin /usr/lib/deadbeef/ddb_customizabletb_gtk2.so
    loading plugin /usr/lib/deadbeef/ddb_customizabletb_gtk3.so
    loading plugin /usr/lib/deadbeef/ddb_dumb.so
    loading plugin /usr/lib/deadbeef/ddb_gvfs.so
    loading plugin /usr/lib/deadbeef/ddb_infobar_gtk2.so
    loading plugin /usr/lib/deadbeef/ddb_infobar_gtk3.so
    loading plugin /usr/lib/deadbeef/ddb_lyrics.so
    loading plugin /usr/lib/deadbeef/ddb_misc_filebrowser_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_misc_quick_search_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_misc_quick_search_GTK3.so
    loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_control_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_control_GTK3.so
    loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan.so
    loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan_GTK3.so
    loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
    loading plugin /usr/lib/deadbeef/ddb_shn.so
    loading plugin /usr/lib/deadbeef/ddb_vis_musical_spectrum_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
    loading plugin /usr/lib/deadbeef/ddb_vis_spectrogram_GTK2.so
    loading plugin /usr/lib/deadbeef/ddb_vis_spectrogram_GTK3.so
    loading plugin /usr/lib/deadbeef/dsp_libsrc.so
    loading plugin /usr/lib/deadbeef/ffap.so
    loading plugin /usr/lib/deadbeef/ffmpeg.so
    loading plugin /usr/lib/deadbeef/flac.so
    loading plugin /usr/lib/deadbeef/gme.so
    loading plugin /usr/lib/deadbeef/in_sc68.so
    loading plugin /usr/lib/deadbeef/lastfm.so
    loading plugin /usr/lib/deadbeef/m3u.so
    loading plugin /usr/lib/deadbeef/mms.so
    loading plugin /usr/lib/deadbeef/mp3.so
    loading plugin /usr/lib/deadbeef/musepack.so
    loading plugin /usr/lib/deadbeef/nullout.so
    loading plugin /usr/lib/deadbeef/opus.so
    loading plugin /usr/lib/deadbeef/oss.so
    loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
    loading plugin /usr/lib/deadbeef/pulse.so
    loading plugin /usr/lib/deadbeef/shellexec.so
    loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
    loading plugin /usr/lib/deadbeef/sid.so
    loading plugin /usr/lib/deadbeef/sndfile.so
    loading plugin /usr/lib/deadbeef/stereo_widener.so
    loading plugin /usr/lib/deadbeef/supereq.so
    loading plugin /usr/lib/deadbeef/tta.so
    loading plugin /usr/lib/deadbeef/vfs_curl.so
    loading plugin /usr/lib/deadbeef/vfs_zip.so
    loading plugin /usr/lib/deadbeef/vorbis.so
    loading plugin /usr/lib/deadbeef/vtx.so
    loading plugin /usr/lib/deadbeef/wavpack.so
    loading plugin /usr/lib/deadbeef/wildmidi.so
    loading plugin /usr/lib/deadbeef/wma.so
    selected output plugin: PulseAudio output plugin
    INFO: loading playlist Default
    INFO: from file /home/felics/.config/deadbeef/playlists/0.dbpl
    [ddb_customizabletb_gtk3] Failed to connect to GTKUI(GTK3), deactivating
    plugin Customizable toolbar for GTKUI(GTK3) failed to connect to dependencies, deactivated.
    infobar-ng: can't find gtkui plugin
    plugin Infobar-ng failed to connect to dependencies, deactivated.
    fb api2
    plugin Quick search failed to connect to dependencies, deactivated.
    replaygain control: can't find gtkui plugin
    plugin Replay Gain Control GTK3 UI failed to connect to dependencies, deactivated.
    rgscangui: gtkui plugin not found
    plugin Replay Gain Scanner GTK3 UI failed to connect to dependencies, deactivated.
    plugin Musical Spectrum failed to connect to dependencies, deactivated.
    plugin Spectrogram failed to connect to dependencies, deactivated.
    gtkui plugin compiled for gtk version: 2.24.31
    Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x84e740)" of type `gboolean'
    ffmpeg: too many extensions, max is 256
    Segmentation Fault
    backtrace() returned 8 addresses
    deadbeef() [0x403ba0]
    /usr/lib/libc.so.6(+0x33a90) [0x7f97a4e3aa90]
    /usr/lib/deadbeef/ffmpeg.so(+0x315e) [0x7f9791d7b15e]
    /usr/lib/deadbeef/ffmpeg.so(+0x31a9) [0x7f9791d7b1a9]
    deadbeef() [0x404bef]
    deadbeef() [0x404e39]
    /usr/lib/libpthread.so.0(+0x72e7) [0x7f97a51b22e7]
    /usr/lib/libc.so.6(clone+0x3f) [0x7f97a4ef354f]

deadbeef has been compiled with:

    ./configure --prefix=/usr \
    --enable-nls \
    --enable-threads \
    --enable-nullout \
    --enable-alsa \
    --enable-oss \
    --enable-pulse \
    --enable-coreaudio \
    --disable-gtk3 \
    --enable-gtk2 \
    --enable-vfs-curl \
    --enable-lfm \
    --enable-artwork \
    --enable-artwork-network \
    --enable-supereq \
    --enable-sid \
    --enable-mp3 \
    --enable-libmad \
    --enable-libmpg123 \
    --enable-ffap \
    --enable-vtx \
    --enable-adplug \
    --disable-hotkeys \
    --enable-vorbis \
    --enable-ffmpeg \
    --enable-flac \
    --enable-sndfile \
    --enable-wavpack \
    --enable-cdda --enable-cdda-paranoia --enable-gme \
    --disable-notify \
    --enable-shellexec --enable-musepack --enable-wildmidi --enable-tta --enable-dca --enable-aac --enable-mms \
    --enable-src --enable-m3u --enable-vfs-zip --enable-converter --enable-artwork-imlib2 --enable-dumb --enable-shn --enable-psf --enable-mono2stereo --enable-shellexecui --enable-alac --enable-wma --enable-pltbrowser --enable-sc68

**Comment by Alexey-Yakovenko** [comment]
Hello. This seems to be a valid bug. There should be a workaround though, before this gets fixed:

edit `~/.config/deadbeef/config`, and delete the line `ffmpeg.enable_all_exts 1`.

**Comment by Alexey-Yakovenko** [comment]
It should be fixed now on both master and 0.7 branches, you'll need to build from 0.7 branch to test the fix, or apply this as a patch: https://github.com/Alexey-Yakovenko/deadbeef/commit/ba4788133c8fc9d7496010bb3450867fef47fc32

**Comment by felixbecker2** [comment]
Thank you for fixing the buffer owerflow.

But I still get `ffmpeg: too many extensions, max is 256`, and don't know what deadbeef then does with it. Does it just completely disable ffmpeg? Or use the first 256 available extensions?

I still consider it as a bug if there is ffmpeg support available but not all extensions provided by ffmpeg can be used.

**Comment by Alexey-Yakovenko** [comment]
Increased the limit to 1024. Hope that's enough, but I don't know what's the max number of ffmpeg file formats.

**Comment by felixbecker2** [comment]
Is a limit necessary?

**Comment by oleksiy-unity3d** [comment]
absolutely.

**Comment by Alexey-Yakovenko** [comment]
absolutely.

(sorry for repost, posted from wrong account the other time)
