### ISSUE TITLE
deadbeef crashes/hangs when ffmpeg cannot play file 

### ISSUE THREAD

**Issue by 5685C4A059D5** [Alexey-Yakovenko/deadbeef#1802]
### Expected behavior
deadbeef skips the file.
### Actual behavior
deadbeef crashes or hangs
### Steps to reproduce the behavior
Play a corrupted (in my case, a mp3) file that ffmpeg cannot decode.

journalctl & gdb output attached.
[gdb.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/1050187/gdb.txt)
[journalctl.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/1050188/journalctl.txt)

**Comment by Alexey-Yakovenko** [comment]
Your build is stripped, therefore doesn't contain debug information, and doesn't really show anything.

You also forgot to specify which OS and deadbeef version you are running.

**Comment by 5685C4A059D5** [comment]
Oh right, forgot that.
Version: 0.7.2
OS: Arch Linux with updated packages, kernel 4.11.2

I'll try a debug build.

**Comment by Alexey-Yakovenko** [comment]
There have been many changes to ffmpeg plugin since the 0.7.2 release, and it's likely that this bug was already fixed on trunk.

**Comment by 5685C4A059D5** [comment]
I downloaded the latest build on sourceforge and the issue is still present.
Gonna compile 0.7.2 debug. Or should I clone master and compile that?

**Comment by Alexey-Yakovenko** [comment]
Are you getting the same issue with static build? That's strange, because ffmpeg in static builds doesn't contain MP3 codec at all.

**Comment by Alexey-Yakovenko** [comment]
It would be best if you run the unstripped build from master, yes. Because that's what I'd be fixing.

**Comment by 5685C4A059D5** [comment]
For the downloaded static build I added mp3 to the format list of the FFMPEG plugin. This allows me to add and play mp3 files (If I don't do this I'm not able to open mp3 files).

This is also the case for the installed 0.7.2 (except I can still play added mp3 files somehow).

**Comment by Alexey-Yakovenko** [comment]
So you have another problem then? Because normally deadbeef is NOT using ffmpeg for playing MP3s.

**Comment by 5685C4A059D5** [comment]
I just tried deadbeef-git and the issue is no longer present.
I added mp3 to ffmpeg plugin format list, like before. libmad isn't installed so I can't add mp3 files unless I did that.
For reference, it was built with this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deadbeef-git

**Comment by Alexey-Yakovenko** [comment]
ok, that means the issue is already fixed on master. Thanks for the info.
